Peru
globaldothealth/list pull request #1343
Opened 2020-11-02 07:48 UTC by fojackson8

Added line to check if "UUID" field is populated before parsing the case

2020-11-02 14:17 UTC, calremmel approved these changes
I think this makes good sense! There are similar checks in some of the other parsers, and if the ID is missing that's certainly a reason to skip inclusion.

Out of curiosity - what do the rows that are missing UUIDs look like? Is it all missing data in such a case, some sort of repetition of headers, or real data that for some reason doesn't get assigned an ID in the source?

2020-11-06 10:09 UTC, iamleeg requested changes

2020-11-06 10:09 UTC, iamleeg commented on ingestion/functions/parsing/peru/peru.py
> +            if entry["UUID"]:
This needs to be `if 'UUID' in entry:`

```
$ python3
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'a': 1, 'b': 2}
>>> if d['c']:
...   print(d['c'])
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'c'
>>> if 'c' in d:
...   print(d['c'])
... 
```

2020-11-10 08:39 UTC, iamleeg approved these changes

2020-11-10 08:39 UTC, merged