Deal with Buddhist calendar year
globaldothealth/list pull request #1367
Opened 2020-11-19 17:51 UTC by AnyaLindstromBattle

Changed parser to deal with use of both Gregorian and Buddhist calendar year.

2020-11-19 17:53 UTC, AnyaLindstromBattle commented
I also changed the folder and file names from 'Thai' to 'Thailand' but this doesn't seem to have gone down well.

2020-11-19 21:44 UTC, calremmel commented
> I also changed the folder and file names from 'Thai' to 'Thailand' but this doesn't seem to have gone down well.

Hmm! Did you change the path in template.yaml?

2020-11-19 21:48 UTC, calremmel requested changes
I'm guessing that CI is failing because template.yaml also needs the new module path. As soon as that is working, I think this looks great.

2020-11-19 21:48 UTC, calremmel commented on ingestion/functions/parsing/thailand/thailand.py
> +    # Some cases are reported using the Buddhist calendar which is 543 years ahead of the Gregorian
Fascinating! We have 540 years before this would cause any confusion, so this looks good to me.

2020-11-20 13:43 UTC, AnyaLindstromBattle commented
Hmm, changed the template.yaml path doesn't seem to have solved it although you're right, I definetly did need to do that. I am just wondering how git actually deals with changes to folder names, as in does it basically create a new folder with the new name, or does it just change the name of the existing folder? If it creates a new folder, does this mean that I have to also add __init__.py and requirements.txt again? If so, this may be why it is failing.

2020-11-20 14:01 UTC, AnyaLindstromBattle commented
Ok so we seem to have solved that particular issue as the tests all pass now... However I don't want all the previous commits to the thailand parser to be lost (i.e. when it was called thai), so ideally want to 'merge' thai and thailand. But may have to speak to our resident Github wizard @iamleeg for help with that. Note to file: don't rename folders and files in this way again.

2020-11-20 15:56 UTC, AnyaLindstromBattle commented
Unfortunately had to delete the old thai folder and replace with this thailand one, so there will be a break in tracking these files.

2020-11-20 15:58 UTC, iamleeg reviewed
Looks like git has now correctly followed the renames! 🎆

2020-11-20 16:00 UTC, AnyaLindstromBattle commented
You're right, nice!

2020-11-24 08:05 UTC, iamleeg approved these changes
Looks like you've addressed @calremmel's request so I'm approving and merging this.

2020-11-24 08:06 UTC, merged