985 add ability to filter cases by dates
globaldothealth/list pull request #1639
Opened 2021-03-18 19:09 UTC by sergioloporto

2021-03-18 19:14 UTC, sergioloporto commented on verification/curator-service/ui/src/components/App.test.tsx
> +    });
@rkassa @scarpino Hello, I'd like to ask you or James if you can take a look at it at your best convenience.
I am trying (in various ways) to:
-check if the searchbox is empty
-check if it has a specific value

However the tests always pass. No matter if the search textfield is empty, and I tell Jest to experct a random string that for sure is not there. Test always passes. I am wondering if there is a problem with my code, or with something else.

2021-03-19 13:57 UTC, sergioloporto commented on verification/curator-service/ui/src/components/App.test.tsx
> +    });
resolved already

2021-03-19 16:18 UTC, iamleeg commented
I'm confused by the test failures. They don't appear to be new, but I'm trying to bisect on main and haven't found the first good commit yet going back to November O_O. The tests that fail seem fairly fundamental so I can't believe that they've _always_ been broken, but I haven't isolated what introduced the failure yet.

2021-03-25 11:40 UTC, iamleeg commented
> I'm confused by the test failures. They don't appear to be new, but I'm trying to bisect on main and haven't found the first good commit yet going back to November O_O. The tests that fail seem fairly fundamental so I can't believe that they've _always_ been broken, but I haven't isolated what introduced the failure yet.

I'm no longer confused by this, it's not a problem on this PR :)

2021-03-25 13:44 UTC, iamleeg approved these changes
Looks great, and thanks for patching up the tests!

2021-03-25 13:45 UTC, merged

2021-03-25 13:48 UTC, maciekz1996 requested changes
Filtering by date works great, well done 🥇 I just noticed that the search guide is not updated to reflect newly added filtering keywords, and also I commented on one file where one variable declaration can be deleted. 

<img width="963" alt="Screen Shot 2021-03-25 at 14 43 51" src="https://user-images.githubusercontent.com/44740625/112483117-063aad00-8d79-11eb-8c4a-059acb5bd2d4.png">

2021-03-25 13:48 UTC, maciekz1996 commented on data-serving/data-service/src/controllers/case.ts
>                      const dataDictionary = yaml.safeLoad(yamlRes.data);
`dataDictionary` variable should be removed as it is no longer used