1807 show highlighted keywords from fulltextsearch
globaldothealth/list pull request #1884
Opened 2021-05-27 08:34 UTC by sergioloporto

![image](https://user-images.githubusercontent.com/51946947/119793612-0b31ef00-bed7-11eb-86f9-ba26a07432c2.png)

2021-06-01 11:52 UTC, maciekz1996 approved these changes
It works well, good job 👍

2021-06-02 15:06 UTC, maciekz1996 reviewed
Overall it works well, I only think that the alert is not as visible as it should be due to it's background color. Also should this be a dismissible alert or perhaps just simple text? 🤔 

<img width="2180" alt="Screen Shot 2021-06-02 at 17 04 22" src="https://user-images.githubusercontent.com/44740625/120505030-e7821380-c3c4-11eb-8ae5-f8f42946c973.png">

2021-06-02 15:10 UTC, sergioloporto commented
> Overall it works well, I only think that the alert is not as visible as it should be due to it's background color. Also should this be a dismissible alert or perhaps just simple text? 🤔
> 
> <img alt="Screen Shot 2021-06-02 at 17 04 22" width="2000" src="https://user-images.githubusercontent.com/44740625/120505030-e7821380-c3c4-11eb-8ae5-f8f42946c973.png">

@maciekz1996  
Hmm, what background color do you suggest? It is not vital information, thus I thought for it to be not eye catching.
Dismissable... if somebody wants to dismiss it, the person can. If the person doesn't want to dismiss it, so doesn't click the X.

Please suggest if you think it's better to fix something

2021-06-03 07:31 UTC, maciekz1996 commented
@sergioloporto 
Maybe something like breadcrumbs / chips (from Material UI) that are visible in LinelistView when some filters are active? 
It would be easier to understand in contrary to just plain text (especially when there will be more active filters)

2021-06-04 13:44 UTC, maciekz1996 commented
@sergioloporto It looks better now in my opinion 👍  One thing that I noticed is that when the user filters the data insted of using SearchBar and Full text search then it is displayed as `country:India` for example. I think it would be better to parse it to `country - India` the same as on the main page when the filters are applied. Just to make things consistent across pages

<img width="967" alt="Screen Shot 2021-06-04 at 15 41 51" src="https://user-images.githubusercontent.com/44740625/120810891-bbdd6580-c54b-11eb-9f2e-0a39069d1175.png">

2021-06-07 14:00 UTC, maciekz1996 requested changes
It works well for single word values, but falls apart for two worded values like United States for example. (See screenshots below)
<img width="983" alt="Screen Shot 2021-06-07 at 15 59 36" src="https://user-images.githubusercontent.com/44740625/121030094-761dd880-c7a9-11eb-8575-516c2ad98036.png">

2021-06-07 14:16 UTC, maciekz1996 commented
@sergioloporto  Also I noticed that when two or more filters are applied there is no margin between chips
<img width="964" alt="Screen Shot 2021-06-07 at 16 15 22" src="https://user-images.githubusercontent.com/44740625/121032530-a2d2ef80-c7ab-11eb-91e5-7033367dc306.png">

2021-06-07 16:57 UTC, sergioloporto commented
@maciekz1996 fixed

2021-06-09 11:25 UTC, maciekz1996 approved these changes
I've just checked and it works great, good job 🏅 I left some comments, but nothing major

2021-06-09 11:25 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +    // const [filterBreadcrumbs, setFilterBreadcrumbs] = React.useState<
You can delete unused code

2021-06-09 11:25 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +    // const theBreadCrumbs = useSelector(selectFilterBreadcrumbs);
Delete unused code

2021-06-09 11:25 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Case.tsx
> +    theSearchArray?: any;
Is this variable being used anywhere? If not then you can delete it

2021-06-09 11:25 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/ViewCase.tsx
> +                            onClick={() => console.log('clicked')}
If `onClick` event is unused you can just delete it

2021-06-10 17:30 UTC, abhidg approved these changes

2021-06-10 17:30 UTC, merged