added UI for change password form in user profile
globaldothealth/list pull request #2023
Opened 2021-07-26 10:34 UTC by sergioloporto

2021-07-28 09:29 UTC, maciekz1996 requested changes

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +import { resetPassword } from '../redux/auth/thunk';
This can be deleted (it won't be used to change password)

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
Many of styles declared here are not in use, please avoid copying unnecessary code from other pages as it leads to less readable code

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +    useEffect(() => {
This is not necessary here, after successful password change user should see snackbar with success message, but no redirect is needed

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +                                                    !passwordVisible,
This should have it's own variable in React state, right now after toggling `oldPassword` visibility `newPassword` visibility changes as well and the other way round. All password inputs should have separate visibility state variable.

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +
Please delete unnecessary `console.log`

2021-07-28 09:29 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +                        {user.googleID === "" && <ChangePasswordFormInProfile />}
Here you should actually be checking if there is `googleId` property in `user` object at all. If not than show password change form. Please change this condition to: `!user.googleID && <.../>`

2021-07-28 10:01 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/Profile.tsx
> +                        {user.googleID && <ChangePasswordFormInProfile />}
Please change this condition to `!user.googleID` you actually want to show change password form to the users that aren't  registered with Google

2021-08-03 18:33 UTC, abhidg approved these changes

2021-08-03 18:34 UTC, merged