2011 map link redirect to dev site
globaldothealth/list pull request #2105
Opened 2021-08-17 10:19 UTC by sergioloporto

TO DO:

**In Staging server:**
add `.env` file in `/verification/curator-service/ui`
with this content:
`REACT_APP_LINK="https://dev-data.covid-19.global.health"`

**In the Production server:**
add `.env` file in `/verification/curator-service/ui`
with this content:
`REACT_APP_LINK="https://global.health"`

2021-08-19 14:03 UTC, maciekz1996 requested changes
I left one comment, apart from that I'm wondering if it is not a better idea to store link to map in `.env` file and just pass it as `href` attribute in the map link? Map link variable would be different for staging and production.

2021-08-19 14:03 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +                                {process.env.REACT_APP_LINK === "https://dev-data.covid-19.global.healt" ?
I think there is a typo in url (missing "h" at the end)

2021-08-24 11:54 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +                                        href="http://dev-map.covid-19.global.health/"
I would suggest to use ternary operator in href directly instead of conditionally rendering two `<a>` components that differ only in href

2021-08-24 14:39 UTC, maciekz1996 approved these changes
Now everything seems fine, just please remove unused code instead of commenting out

2021-08-24 14:40 UTC, maciekz1996 reviewed
Add also it seems that there is something wrong with the tests

2021-08-25 07:17 UTC, sergioloporto commented
@maciekz1996 please take a look

2021-08-25 07:32 UTC, maciekz1996 commented
@sergioloporto Now everything looks good

2021-08-31 14:51 UTC, abhidg approved these changes

2021-08-31 15:28 UTC, merged