add country to sources
globaldothealth/list pull request #2224
Opened 2021-11-05 14:51 UTC by abhidg

- curator: Add iso-3166-1 to dependencies
- schemas: Add countryCodes to sources
- curator: Add countryCodes field

2021-11-05 14:53 UTC, jim-sheldon approved these changes

2021-11-05 16:17 UTC, iamleeg requested changes
Don't modify sources.schema.json, add a migration. Otherwise the historical information that the countryCodes field was added is missing from history, and it's likely that production and local databases would get out of sync as the prod db already thinks it's migrated past this level.

2021-11-05 21:57 UTC, jim-sheldon approved these changes

2021-11-08 09:54 UTC, iamleeg approved these changes
thank you!

2021-11-08 11:54 UTC, merged