added feedback link
globaldothealth/list pull request #2374
Opened 2022-01-19 11:19 UTC by sergioloporto

2022-01-19 17:22 UTC, maciekz1996 requested changes

2022-01-19 17:22 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +                                className={`${classes.link} ${classes.lastLink}`}
It is a good practice to use library like `clsx` in order to use two class names. This library is already installed and used in this project.

2022-01-19 17:22 UTC, maciekz1996 commented on verification/curator-service/ui/src/components/App/App.tsx
> +                                href="mailto:info@global.health?subject=Feedback regarding Global.health map"
Subject should be changed to `Feedback regarding Global.health data portal`

2022-01-20 09:37 UTC, maciekz1996 approved these changes
Looking good 👍

2022-01-20 09:53 UTC, abhidg approved these changes

2022-01-20 09:53 UTC, merged